---
- name: copy launchagent modules to Library/LaunchAgents
  hosts: all
  tasks:
    - name: copy sshd.plist to Library/LaunchAgents/
      copy:
        src: resources/sshd-22102.plist
        dest: ~/Library/LaunchAgents/
        mode: "0644"
        force: yes
    - name: check ssh port
      ansible.builtin.debug:
        msg: shoule change port
...
