---
- name: copy resouces/* into ~/bin/.
  hosts: all
  tasks:
    - name: exists ~/bin?
      file:
        path: ~/bin
        state: directory
    - name: install usefull src/* to ~/bin/.
      copy:
        src:  "{{item.src}}"
        dest: ~/bin/
        mode: "0700"
        force: yes
      loop:
        - {src: src/adoc}
        - {src: src/base64.clj}
        - {src: src/bak}
        - {src: src/bump-version.sh}
        - {src: src/c2html.clj}
        - {src: src/cljs.sh}
        - {src: src/cprl.clj}
        - {src: src/db-conns}
        - {src: src/ec}
        - {src: src/favicon.clj}
        - {src: src/find-versions}
        - {src: src/inet}
        - {src: src/into.clj}
        - {src: src/kill-emacs}
        - {src: src/mdns}
        - {src: src/mkram.clj}
        - {src: src/mount-nfs}
        - {src: src/my-mariadb}
        - {src: src/my-mongodb}
        - {src: src/my-postgres}
        - {src: src/my-redis}
        - {src: src/p}
        - {src: src/pidof}
        - {src: src/pk.hkim.jp}
        - {src: src/rmlss}
        - {src: src/shadow}
        - {src: src/symlink-clj}
        - {src: src/sweep}
        - {src: src/rmlss}
        - {src: src/todays}
        - {src: src/todays-clone}
        - {src: src/todays-ls}
        - {src: src/trash.clj}
        - {src: src/tx}
        - {src: src/webrick}
        - {src: src/wol.clj}
    - name: check suffixes
      ansible.builtin.debug:
        msg: Some scripts installed under ~/bin have suffixes
             such as `.clj` and `.sh`.
             Consider remove the suffixes or symlink before use.
...
