---
- name: copy utils/* into ~/bin/
  hosts: all
  tasks:
    - name: exists ~/bin?
      file:
        path: ~/bin
        state: directory
    - name: exists ~/clojure folder?
      file:
        path: ~/clojure
        state: directory
    - name: install wol.edn to ~/clojure
      copy:
        src: utils/wol.edn
        dest: ~/clojure/
        mode: 0600
        force: yes
    - name: install usefull(?) utils/* to ~/bin/
      copy:
        src:  "{{ item.src }}"
        dest: ~/bin/
        mode: "0700"
        force: yes
      loop:
        - {src: utils/adoc}
        - {src: utils/base64.clj}
        - {src: utils/bak}
        - {src: utils/bump-version.sh}
        - {src: utils/c2html.clj}
        - {src: utils/cprl.clj}
        - {src: utils/db-conns}
        - {src: utils/ec}
        - {src: utils/favicon.clj}
        - {src: utils/inet}
        - {src: utils/into.clj}
        - {src: utils/kill-emacs}
        - {src: utils/mdns}
        - {src: utils/mkram.clj}
        - {src: utils/mount-nfs}
        - {src: utils/my-mariadb}
        - {src: utils/my-mongodb}
        - {src: utils/my-postgres}
        - {src: utils/my-redis}
        - {src: utils/p}
        - {src: utils/pidof}
        - {src: utils/pk.hkim.jp}
        - {src: utils/rmlss}
        - {src: utils/shadow}
        - {src: utils/symlink-clj}
        - {src: utils/sweep}
        - {src: utils/rmlss}
        - {src: utils/todays}
        - {src: utils/todays-clone}
        - {src: utils/todays-ls}
        - {src: utils/trash.clj}
        - {src: utils/tx}
        - {src: utils/webrick}
        - {src: utils/wol.clj}
    - name: check suffixes
      ansible.builtin.debug:
        msg: Some scripts installed under ~/bin have suffixes
             such as `.clj` and `.sh`.
             Consider remove the suffixes or symlink before use.
...
