---
- name: copy src/* into ~/bin/
  hosts: all
  tasks:
    - name: exists ~/bin?
      file:
        path: ~/bin
        state: directory
    - name: install usefull src/* to ~/bin/
      copy:
        src:  "{{item.src}}"
        dest: "{{item.dest}}"
        mode: "0700"
        force: yes
      loop:
        - {src: src/adoc.sh, dest: ~/bin/adoc}
        - {src: src/bak.sh, dest: ~/bin/bak}
        - {src: src/base64.clj, dest: ~/bin/base64}
        - {src: src/bump-version.sh, dest: ~/bin/bump-version}
        - {src: src/c2html.clj, dest: ~/bin/c2html}
        - {src: src/cljs.sh, dest: ~/bin/cljs.sh}
        - {src: src/cprl.clj, dest: ~/bin/cprl}
        - {src: src/db-conns.sh, dest: ~/bin/db-conns}
        - {src: src/ec.sh, dest: ~/bin/ec}
        - {src: src/favicon.clj, dest: ~/bin/favicon}
        - {src: src/find-versions.sh, dest: ~/bin/find-versions}
        - {src: src/hello.js, dest: ~/bin/hello.js}
        - {src: src/inet.sh, dest: ~/bin/inet}
        - {src: src/into.clj, dest: ~/bin/into.clj}
        - {src: src/kill-emacs.sh, dest: ~/bin/kill-emacs}
        - {src: src/killj.sh, dest: ~/bin/killj}
        - {src: src/killp.sh, dest: ~/bin/killp}
        - {src: src/mdns, dest: ~/bin/mdns}
        - {src: src/mkram.clj, dest: ~/bin/mkram}
        - {src: src/mount-nfs.sh, dest: ~/bin/mount-nfs}
        - {src: src/my-mariadb, dest: ~/bin/my-mariadb}
        - {src: src/my-mongodb, dest: ~/bin/my-mongodb}
        - {src: src/my-postgres, dest: ~/bin/my-postgres}
        - {src: src/my-redis, dest: ~/bin/my-redis}
        - {src: src/node-serv.js, dest: ~/bin/node-serv.js}
        - {src: src/outdated.clj, dest: ~/bin/outdated}
        - {src: src/p, dest: ~/bin/p}
        - {src: src/pidof.sh, dest: ~/bin/pidof}
        - {src: src/pk.hkim.jp, dest: ~/bin/pk.hkim.jp}
        - {src: src/projects.sh, dest: ~/projects/projects.sh}
        - {src: src/psj.sh, dest: ~/bin/psj}
        - {src: src/refresh-m2.sh, dest: ~/bin/refresh-m2}
        - {src: src/rm-local-snapshots.sh, dest: ~/bin/rm-local-snapshots}
        - {src: src/rm-trailing-spaces.sh, dest: ~/bin/rm-trailing-spaces}
        - {src: src/shadow, dest: ~/bin/shadow}
        - {src: src/symlink-clj, dest: ~/bin/symlink-clj}
        - {src: src/sweep.rb, dest: ~/bin/sweep}
        - {src: src/to-ramdisk.sh, dest: ~/bin/to-ramdisk}
        - {src: src/todays-clone.sh, dest: ~/bin/todays-clone}
        - {src: src/todays-ls.sh, dest: ~/bin/todays-ls}
        - {src: src/todays.sh, dest: ~/bin/todays}
        - {src: src/trash.clj, dest: ~/bin/trash}
        - {src: src/tx.sh, dest: ~/bin/tx}
        - {src: src/webrick.rb, dest: ~/bin/webrick}
        - {src: src/wol.clj, dest: ~/bin/wol}
    - name: check suffixes
      ansible.builtin.debug:
        msg: currently no messages.
...
