---
- name: copy utils/* into ~/bin/
  hosts: all
  tasks:
    - name: copy launchagent modules
      copy:
        src: utils/ssh-22102.plist
        dest: ~/Library
        mode: "0644"
        force: yes
    - name: check ssh port
      ansible.builtin.debug:
        msg: shoule change port
    - name: exists ~/bin?
      file:
        path: ~/bin
        state: directory
    - name: install usefull(?) utils/* to ~/bin/
      copy:
        src:  "{{item.src}}"
        dest: ~/bin/
        mode: "0700"
        force: yes
      loop:
        - {src: resources/adoc}
        - {src: resources/base64.clj}
        - {src: resources/bak}
        - {src: resources/bump-version.sh}
        - {src: resources/c2html.clj}
        - {src: resources/cprl.clj}
        - {src: resources/db-conns}
        - {src: resources/ec}
        - {src: resources/favicon.clj}
        - {src: resources/inet}
        - {src: resources/into.clj}
        - {src: resources/kill-emacs}
        - {src: resources/mdns}
        - {src: resources/mkram.clj}
        - {src: resources/mount-nfs}
        - {src: resources/my-mariadb}
        - {src: resources/my-mongodb}
        - {src: resources/my-postgres}
        - {src: resources/my-redis}
        - {src: resources/p}
        - {src: resources/pidof}
        - {src: resources/pk.hkim.jp}
        - {src: resources/rmlss}
        - {src: resources/shadow}
        - {src: resources/symlink-clj}
        - {src: resources/sweep}
        - {src: resources/rmlss}
        - {src: resources/todays}
        - {src: resources/todays-clone}
        - {src: resources/todays-ls}
        - {src: resources/trash.clj}
        - {src: resources/tx}
        - {src: resources/webrick}
        - {src: resources/wol.clj}
    - name: check suffixes
      ansible.builtin.debug:
        msg: Some scripts installed under ~/bin have suffixes
             such as `.clj` and `.sh`.
             Consider remove the suffixes or symlink before use.
...
